version: '3'
services:
  service:
    image: ${SERVICE_IMAGE}:${SERVICE_TAG}
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - 80:80
    networks:
      - box-organization-network
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - box-organization-network
    volumes:
      - box-organization-db-data:/var/lib/postgresql/data/

volumes:
  box-organization-db-data:

networks:
  box-organization-network:
