spring:
  application:
    name: box-organization-be
  flyway:
    enabled: false
    baseline-on-migrate: true
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
