name: Deploy

on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Test and Build
        run: make test build

      - name: Push tagged docker image
        run: make push-image

      - name: Deploy
        run: make deploy
